### ISSUE TITLE
ERC track integration doesn't respect track config

### ISSUE THREAD

**Issue by strugee** [TheBB/spaceline#100]
I sit in a lot of IRC channels, which means that I have a lot of customizations to make ERC's `track` module quiet and thus useful. As far as I can tell, the ERC integration in spaceline doesn't respect this configuration. Here's [my .emacs](https://github.com/strugee/dots/blob/master/.emacs).

I'm on Emacs 24.5.1 on OS X. If there's anything else I can look at, I'd be happy to oblige.

**Comment by strugee** [comment]
@TheBB I wonder if you've seen this? I can still reproduce this.

**Comment by vincentbernat** [comment]
This should be fixed in ca85233b443216f8519c401c58af6807b6d31740.

**Comment by pjones** [comment]
ERC tracking works for me after applying ca85233.

**Comment by TheBB** [comment]
Good call, I'd forgotten about this issue. Thanks.
