### ISSUE TITLE
Spaceline is blank in pdf-tools buffers

### ISSUE THREAD

**Issue by Andre0991** [TheBB/spaceline#106]
Hi @TheBB.

I'm using Spacemacs and the `pdf-tools` layer. The spaceline is always blank in `pdf-tools` buffers. 

I suspect the spaceline format has been changed and the part of the code that deals with `pdf-tools` still uses the old way or something like that.

**Comment by TheBB** [comment]
https://github.com/TheBB/spaceline/pull/99

**Comment by Andre0991** [comment]
Oh, ok. I'll follow that issue then.

**Comment by et2010** [comment]
I think this issue is reoccurring. With all the packages updated, I still got the same problem. The fix mentioned in the other issue doesn't work for me.
