### ISSUE TITLE
Feature Request: Use `all-the-icons` to beautify the modeline

### ISSUE THREAD

**Issue by CestDiego** [TheBB/spaceline#107]
https://github.com/domtronn/all-the-icons.el/wiki/Mode-Line <3

**Comment by nixmaniack** [comment]
The author has now also added sample[ spaceline configuration](https://github.com/domtronn/all-the-icons.el/wiki/Spaceline) but I would be better to have it in spaceline itself as another theme!

**Comment by TheBB** [comment]
Now that there's a separate package for this I don't want to step on @domtronn's toes.
