### ISSUE TITLE
How to get rid of "Loading a theme can run Lisp code.  Really load?"

### ISSUE THREAD

**Issue by ninrod** [TheBB/spaceline#108]
when I start my emacs, with spaceline loaded, I'm always greeted with: 

```txt
Loading a theme can run Lisp code.  Really load? (y or n)
```

then 

```txt
Treat this theme as safe in future sessions? (y or n)
```

Is there a way to get rid of those annoying dialogs?

**Comment by TheBB** [comment]
Spaceline doesn't load any themes.

**Comment by ninrod** [comment]
oh...

it must be the stock spacemacs-theme then.
