### ISSUE TITLE
Separator incorrect color when evil-state faces are customized.

### ISSUE THREAD

**Issue by haesken** [TheBB/spaceline#11]
Hey, I'm trying to customize the colors of spaceline to match my theme (monokai), particularly the colors for evil-state. When I customize the `spaceline-evil-*` faces' backgrounds the separator does not match anymore. I can see it is trying to match but is not doing so correctly.

My spaceline config:

    (require-package 'spaceline)
    (require 'spaceline-config)
    (spaceline-spacemacs-theme)
    (setq powerline-default-separator 'wave)
    (spaceline-toggle-minor-modes-off)
    (spaceline-toggle-hud-off)
    (setq spaceline-highlight-face-func 'spaceline-highlight-face-evil-state)

    (set-face-attribute 'spaceline-evil-emacs nil :background "#be84ff")
    (set-face-attribute 'spaceline-evil-insert nil :background "#5fd7ff")
    (set-face-attribute 'spaceline-evil-motion nil :background "#ae81ff")
    (set-face-attribute 'spaceline-evil-normal nil :background "#a6e22e")
    (set-face-attribute 'spaceline-evil-replace nil :background "#f92672")
    (set-face-attribute 'spaceline-evil-visual nil :background "#fd971f")

And a screenshot of the problem:

![spaceline](https://cloud.githubusercontent.com/assets/878200/10232093/29020304-684c-11e5-9bfc-dbe6f5e7a135.png)

**Comment by TheBB** [comment]
It works for me after calling `(powerline-reset)`.

**Comment by TheBB** [comment]
To expand, the powerline separator functions are memoized (cached), so you need to reset them after certain tweaks. This is presumably one of them.

**Comment by haesken** [comment]
Yep that works, thanks.
