### ISSUE TITLE
Make it easier to customize default segment order

### ISSUE THREAD

**Issue by dschoepe** [TheBB/spaceline#112]
I wanted to change the order in which the default segments are displayed in the modeline, for example by moving buffer-position and hud to the left-hand side. At the moment, the best way I could find of doing so is to modify the order directly in `spaceline--theme`. 

Putting the default segments on the left and right sides into `defcustom`s would make this process cleaner and remove the need to modify the spaceline source directly.

**Comment by TheBB** [comment]
Is https://github.com/TheBB/spaceline/pull/114 good enough?

**Comment by dschoepe** [comment]
Yes, #114 solves this for me.

**Comment by indigoviolet** [comment]
It doesn't look like #114 was ever merged, this should be reopened
