### ISSUE TITLE
Separators are too small when using a font with increased size (or HiDPI settings)

### ISSUE THREAD

**Issue by IvanMalison** [TheBB/spaceline#113]
See http://imgur.com/a/kzn5I

spaceline-compile does not ameliorate the issue. I suspect that this situtation needs to be detected and the svgs need to be regenerated.

**Comment by TheBB** [comment]
Report to powerline please, the separators come from there.

**Comment by TheBB** [comment]
Is `powerline-scale` set correctly?

**Comment by TheBB** [comment]
`powerline-height`, I mean.

**Comment by IvanMalison** [comment]
Ahhh okay, that seems to fix things. So the problem arises when the font size results in a modeline larger than what is set by powerline height. Thanks for the tip.
