### ISSUE TITLE
battery segment triggers wrong-type-argument during early startup

### ISSUE THREAD

**Issue by lunaryorn** [TheBB/spaceline#115]
The `battery` segment triggers the following error during early startup, i.e. while init.el is still loading:

```
Error during redisplay: (eval (spaceline-ml-lunaryorn)) signaled (wrong-type-argument stringp nil)
```

A stacktrace reveals that spaceline tries to apply `s-trim` to `nil`, because it unconditionally calls `s-trim` on the result of `spaceline--fancy-battery-mode-line` which in turn [returns nil if there's no battery status](https://github.com/TheBB/spaceline/blob/3da3396fea7f1dd178e8b807775ef92e46939be9/spaceline-segments.el#L378)—which happens during early startup because the battery status is queried asynchronously through timers.

The fix would either be to check the result of that function before applying `s-trim` or to make `spaceline--fancy-battery-mode-line` return an empty string if the battery status is empty.

I can prepare a pull request, but I'd like to ask first which fix you prefer and whether this package is subject to FSF copyright assignments.

**Comment by TheBB** [comment]
Thanks! The best would be if the segment as a whole returned nil in this case, so I would go with the first. No FSF paperwork needed here.

**Comment by lunaryorn** [comment]
@TheBB Thanks.  I've opened #116.
