### ISSUE TITLE
Spaceline & fill-column-indicator

### ISSUE THREAD

**Issue by igorepst** [TheBB/spaceline#12]
On spacemacs develop branch with latest spaceline, if fill-column-indicator is disabled, the spaceline is not shown at all (only empty space is visible). The error is: "Error during redisplay: (eval (spaceline--prepare)) signaled (void-variable fci-mode)"

**Comment by TheBB** [comment]
Yeah I know, it should be fixed in https://github.com/TheBB/spaceline/commit/e7326fe61207440de741abbb5f54b13e5d5488a6, so just update when that reaches MELPA in an hour or two.

**Comment by igorepst** [comment]
Thanks
