### ISSUE TITLE
Does spaceline support width like (-3 . "%p")

### ISSUE THREAD

**Issue by lukertty** [TheBB/spaceline#121]
I want the length of buffer-position always equal to 3. (That means "Bottom" -> "Bot")

[(width rest…)](https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode-Line-Data.html) can do:
```elisp
(setq mode-line-format (quote (
    (-3 . "%p")
   )))
```

How to get it worked in spaceline?

I have tryed
```elisp
(spaceline-define-segment buffer-position
  "The current approximate buffer position, in percent."
  (-3 . "%p"))
```

But getting error `Error during redisplay: (eval (spaceline-ml-main)) signaled (invalid-function -3) `

Thanks

**Comment by TheBB** [comment]
You have to quote the return value, otherwise it is being evaluated.

You can also try calling `format-mode-line` in your segment directly.
