### ISSUE TITLE
onclick property

### ISSUE THREAD

**Issue by jwintz** [TheBB/spaceline#126]
Hello,

I've been through [defining a segment](https://github.com/TheBB/spaceline#defining-a-segment) deeply and understood at some point that user defined segments should be passed as an argument to `spaceline-spacemacs-theme` whenever using it (which should be explicitly stated in the README).

However, my segments are now working perfectly, but I would like to add some "mouse clicked" actions to them.

Is that possible ? I've not found this in the documentation nor in the issues.

Wonderful package anyways, many thanks @TheBB !

**Comment by TheBB** [comment]
You have to add text properties to the output. For example, the `local-map` property, as is done here:

https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el#L52-L72

Documented in the emacs lisp reference manual:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Special-Properties.html#Special-Properties

**Comment by jwintz** [comment]
Thanks for the prompt answer.

So far I have this working:

```
  (spaceline-define-segment prolusion-upgrades-count
    (when (string= major-mode "prolusion/dashboard-mode")
      (unless prolusion-upgrade-count
        (save-window-excursion
          (package-list-packages)
          (package-menu-mode)
          (setq prolusion-upgrade-count (length (package-menu--find-upgrades)))
          (kill-buffer (get-buffer "*Packages*"))))
      (if (> prolusion-upgrade-count 0)
          (format " %s" prolusion-upgrade-count (format " %s" prolusion-upgrade-count)))))
  (setq powerline-default-separator 'wave)
  (setq spaceline-highlight-face-func 'spaceline-highlight-face-modified)
  (setq spaceline-display-default-perspective t)
  (setq spaceline-toggle-window-number-on-p t)
  (spaceline-spacemacs-theme 'narrow 'prolusion-upgrades-count)
  (spaceline-helm-mode +1)
```

But when I add propertize to the `(format)` function, everything breaks down.

BTW, took me ages to figure out to add `'narrow 'prolusion-upgrades-count` to `(spaceline-spacemacs-theme)` which is wonderful by the way ;-)

**Comment by jwintz** [comment]
And for the record, can't get `package-refresh-contents` to work with package `async`, after hours.

**Comment by jwintz** [comment]
Here's what I've came up with, but it gives a blank spaceline:

```
  (spaceline-define-segment prolusion-upgrades-count
    (when (string= major-mode "prolusion/dashboard-mode")
      (unless prolusion-upgrade-count
        (save-window-excursion
          (package-list-packages)
          (package-menu-mode)
          (setq prolusion-upgrade-count (length (package-menu--find-upgrades)))
          (kill-buffer (get-buffer "*Packages*"))))
      (if (> prolusion-upgrade-count 0)
          (format " %s"
                  (propertize prolusion-upgrade-count
                              'mouse-face 'mode-line-highlight
                              'help-echo (concat (prolusion-upgrade-count)
                                                 "\nmouse-1: Display minor mode menu")
                              'local-map (let ((map (make-sparse-keymap)))
                                           (define-key map
                                             [mode-line down-mouse-1]
                                             (prolusion-upgrade-packages))))))))
```

**Comment by TheBB** [comment]
Well, I don't know what error is reported (look in the messages buffer), but I note that you have mapped mouse click to `(prolusion-upgrade-packages)` instead of `'prolusion-upgrade-packages`. In other words you are running the function at modeline creation time and binding mouseclick to the return value of that function, which is presumably not what you are trying to do.

**Comment by TheBB** [comment]
Note that in my code, `powerline-mouse` returns a function to bind, it is not the function to which we want to bind.

**Comment by deb0ch** [comment]
Looks like the initial request for information has been fulfilled, closing this.
