### ISSUE TITLE
Can't display perspective name

### ISSUE THREAD

**Issue by angrybacon** [TheBB/spaceline#127]
Here is what I've tried:

```elisp
(spaceline-install
 `(...)
 `(...
   (safe-persp-name (get-frame-persp))
   ...))
```

Persp-mode is fully functional, other segments show up as intended, evaluating `(safe-persp-name (get-frame-persp))` gives me what I expect, but the perspective doesn't show in the mode-line.

**Comment by TheBB** [comment]
You can't put arbitrary forms to be evaluated in there like that. Spaceline will be looking for a nonexistent segment called safe-persp-mode. Please do read the documentation.

**Comment by angrybacon** [comment]
Right, that makes sense.

Thing is, I originally tried with the already defined `persp-name` segment which didn't display anything. What can I provide to help debug this?

**Comment by angrybacon** [comment]
Looks I had something else in my configuration breaking this, I cannot reproduce it after restarting Emacs. Works as expected when using `persp-name` directly.
