### ISSUE TITLE
Easily move the line number to the start of spaceline

### ISSUE THREAD

**Issue by dakrone** [TheBB/spaceline#128]
First, thanks for separating spaceline from spacemacs so it can be used separately. I appreciate it!

I was wondering though, can an option be added to move the line number segment  to the beginning of the modeline? I frequently run into a problem where my buffer is not wide enough, so the line number ends up being cut off, which is really too bad as I tend to need the line number quite frequently (correlating backtraces to lines of code for exceptions and so forth).

Or, if there's no way to force it to be at the beginning, is there a way to force it to *always* be visible in the modeline, even if it means hiding something else when the buffer is not very wide?

**Comment by TheBB** [comment]
I don't want to create too many options like this because it will be too complicated in the end. Your best bet is to reorder all the segments to your liking and recompile the modeline.

**Comment by dakrone** [comment]
Okay, I'll close this then, thanks!
