### ISSUE TITLE
(spaceline-spacemacs-theme) does not change modeline

### ISSUE THREAD

**Issue by kluge** [TheBB/spaceline#13]
I tried

```
(require 'spaceline-config)
(spaceline-spacemacs-theme)
```

as suggested in the README, but the modeline does not change at all. All I get is the following in \*Messages\*:

```
("%e" (:eval (spaceline--prepare)))
```

I don't know how I could debug it further. I'm using GNU Emacs 24.5.1 (i586-pc-linux-gnu, GTK+ Version 3.16.6) of 2015-09-20 on binet, modified by Debian.

**Comment by TheBB** [comment]
All that function does is this (minus a few things we won't worry about while debugging)

* Set `spaceline-right` and `spaceline-left` (see values in `spaceline-config.el`
* Set `mode-line-format` to `("%e" (:eval (spaceline--prepare)))`

If you do this "manually", does it work then?

**Comment by kluge** [comment]
Eivind Fonn <notifications@github.com> writes:

> All that function does is this (minus a few things we won't worry about while debugging)
>
> * Set `spaceline-right` and `spaceline-left` (see values in `spaceline-config.el`
> * Set `mode-line-format` to `("%e" (:eval (spaceline--prepare)))`
>
> If you do this "manually", does it work then?
>

It seems like that since I was evaluating that in *scratch*, the
mode-line-format was set globally. But due to an existing mode line
package that I had, the buffer-local value stayed the same. So I only
saw the old modeline.

Once I removed loading that from my init file and added spaceline,
things worked out.

-- 
Kari

**Comment by TheBB** [comment]
Great :+1:
