### ISSUE TITLE
With scrollbar, the spaceline is truncated. [refer images]

### ISSUE THREAD

**Issue by hhnr** [TheBB/spaceline#135]
With scrollbar:

![all_with_scrollbar](https://cloud.githubusercontent.com/assets/3027568/24078315/5c263f72-0c90-11e7-849c-d3386c138164.png)

![bottom_with_scroll_bar](https://cloud.githubusercontent.com/assets/3027568/24078317/65aa4dea-0c90-11e7-917a-380dd8b3e4ff.png)

Without scrollbar:

![top](https://cloud.githubusercontent.com/assets/3027568/24078318/6b7c4494-0c90-11e7-9d88-6eff1b9842ff.png)
![bottom](https://cloud.githubusercontent.com/assets/3027568/24078319/7170e03a-0c90-11e7-94a6-de2d481512b3.png)

**Comment by rmolinari** [comment]
On my machine it is the other way around. When I have a scrollbar the modeline looks right. When I don't have a scrollbar the buffer percentage and HUD are truncated.

**Comment by TheBB** [comment]
Closing this for https://github.com/TheBB/spaceline/issues/163

**Comment by MoHKale** [comment]
If anyone is experiencing a similair issue but reversed. I.E. you get something like image 1 when the scrollbar is inactive, but it looks fine when it is active you may be using `(toggle-scroll-bar -1)` in your emacs config ~like I was~ where you should instead be using `(scroll-bar-mode -1)`. Why the two aren't functionally equivalent, I don't know 😅😅😅. but making that change fixed it for me.

**Comment by SirSharpest** [comment]
@mohkale thank you so much, this update solved a long annoying issue for me!
