### ISSUE TITLE
Error with mu4e

### ISSUE THREAD

**Issue by justmytwospence** [TheBB/spaceline#14]
[mu4e](https://github.com/djcb/mu) puts the current search query into the modeline. When spaceline is activated, this somehow causes the whole modeline to go completely blank with this error:

```
Error during redisplay: (eval (spaceline--prepare)) signaled (wrong-type-argument listp #("maildir:\"/work/Inbox\"" 0 21 (face mu4e-modeline-face))) [6 times]
```

Any quick way to fix this?

**Comment by TheBB** [comment]
Thanks for the report. Can you check the values of mode-line-format and global-mode-string when it happens?

**Comment by justmytwospence** [comment]
mode-line-format:
```
("%e" (:eval (spaceline--prepare)))
```
global-mode-string:
```
#("maildir:\"/personal/Inbox\"" 0 25 (face mu4e-modeline-face))
```

**Comment by TheBB** [comment]
Okay, thanks. So `global-mode-string` is a string, and not (as is typically the case) a list. I'll have a fix for this quite soon.

**Comment by TheBB** [comment]
Should be fixed in https://github.com/TheBB/spaceline/commit/f18d0ee4330d51a44b49e2f306d9ed7d7fe4f5bb. It'll be on MELPA in a few hours.

**Comment by justmytwospence** [comment]
woot thanks

**Comment by TheBB** [comment]
Okay, it's online now.
