### ISSUE TITLE
Multiple spaceline functions do not work

### ISSUE THREAD

**Issue by jabranham** [TheBB/spaceline#141]
I'm not sure if this is related to #80 or not.

Calling `spaceline-toggle-projectile-root-on` does nothing for me (I don't get an error either). 

Here's how I set up spaceline:

```emacs-lisp
(use-package spaceline-config
  :ensure spaceline
  :config
  (setq spaceline-window-numbers-unicode t)
  (spaceline-spacemacs-theme)
  (spaceline-helm-mode)
  (spaceline-info-mode)
  (spaceline-toggle-buffer-encoding-abbrev-off)
  (add-hook 'after-init-hook #'spaceline-toggle-minor-modes-off))
```

**Comment by jabranham** [comment]
Actually, I've noticed that several spaceline functions don't seem to do anything. For example, `M-x spaceline-toggle-battery-on` doesn't do much (I have fancy-battery installed, and calling `fancy-battery-mode` shows the info in the mode line).

**Comment by guygurari** [comment]
I have the same problem. Even a simple custom segment that only returns a string doesn't work.

```
  (spaceline-define-segment my-projectile
    "My own spaceline projectile segment, returning the project name."
    "alpha"
    )

  (spaceline-toggle-my-projectile-on)
```

**Comment by TheBB** [comment]
@guygurari doesn't look like the same issue to me. Judging from your code, you haven't put your segment in the modeline.

**Comment by guygurari** [comment]
Can you please explain how to put the segment in the mode line? I thought defining and turning it on was enough. 

I should say that `spaceline-toggle-projectile-root-on` also doesn't work for me, as well as some other built-in segments.

**Comment by TheBB** [comment]
https://github.com/TheBB/spaceline#compiling-a-mode-line

You have to pass the list of segments you want to the `spaceline-compile` function.

**Comment by TheBB** [comment]
> I should say that spaceline-toggle-projectile-root-on also doesn't work for me, as well as some other built-in segments.

This segment is also not in the default modelines.

https://github.com/TheBB/spaceline#turning-segments-on-and-off

It's listed under segments that are defined but not used by default.

**Comment by TheBB** [comment]
`fancy-battery-mode` works for me. When I turn the mode on and the segment is in my modeline (which it is, by default) I do get battery information.

So in conclusion I don't see any bugs here.

**Comment by jabranham** [comment]
Thanks. I think I misunderstood what "used by default" meant. I set up my own modeline and it works well. Thanks!

**Comment by guygurari** [comment]
I was also confused by the documentation, because I did not realize toggling modes is not enough. It works for me now as well. Thanks for clearing it up!
