### ISSUE TITLE
string-trim not defined (sometimes)

### ISSUE THREAD

**Issue by ambihelical** [TheBB/spaceline#148]
For one .txt file I have, when it is the first file loaded, spaceline doesn't display anything for the modeline and generates the following error in `*Messages*`:

`Error during redisplay: (eval (spaceline-ml-main)) signaled (void-function string-trim) [8 times]`

I added `(require 'subr-x)` to the top of spaceline.el to define string-trim, and the problem went away.  

Another data point, if I load a file without this problem first, and then the problem file, the mode line displays correctly.

**Comment by TheBB** [comment]
Thanks!

**Comment by deb0ch** [comment]
Oooops, I think I'm the one who brought that `string-trim` in :sweat_smile: 

Thanks all :smile_cat:
