### ISSUE TITLE
Spaceline becomes blank when click on pdfview link in org buffer

### ISSUE THREAD

**Issue by et2010** [TheBB/spaceline#149]
I've recorded an animated gif for demonstration:
![pdfview](https://user-images.githubusercontent.com/11584902/27758355-95073b56-5e44-11e7-820f-c7e1f1bc2da6.gif)
Note that when I switched back to the org buffer, the spaceline below it also became blank.

**Comment by et2010** [comment]
I think it's related to #147

**Comment by TheBB** [comment]
It is #147.
