### ISSUE TITLE
Skip colour alternation or let it extend to the left

### ISSUE THREAD

**Issue by lunaryorn** [TheBB/spaceline#15]
I'd like to add a segment to the front of `spacemacs-left`, while keeping the colours of the existing segments unchanged.  IOW, the new segment should not change colour alternation for the other segments.

**Comment by lunaryorn** [comment]
@TheBB Any news on this?

**Comment by TheBB** [comment]
Can you try https://github.com/TheBB/spaceline/commit/cf559cdad64b37389daa6261cdd3f98d26765f1e with `:skip-alternate t`?

**Comment by lunaryorn** [comment]
I'll try tomorrow, ok?

**Comment by lunaryorn** [comment]
@TheBB Works like a charm :) Thanks!
