### ISSUE TITLE
Cannot create conditional face

### ISSUE THREAD

**Issue by thblt** [TheBB/spaceline#153]
Documentation about the `:face` segment property states:

> `:face`: The face in which to render the  segment.  This may be either a face or a form evaluating to a face. 

But the following code (from `emacs -q`) doesn't work:

``` emacs-lisp
(require 'spaceline-config)

(spaceline-compile 'thblt
		   '(("Hello" :face bold)
		     ("World" :face (if t bold italic)))
		   '())

(setq-default mode-line-format '("%e" (:eval (spaceline-ml-thblt))))
```

The mode line shows absolutely nothing, and evaluating the generated `spaceline-ml-thblt` raises an error:

```
Debugger entered--Lisp error: (error "Invalid face" if t bold italic)
  internal-get-lisp-face-attribute((if t bold italic) :inverse-video nil)
  face-attribute((if t bold italic) :inverse-video nil default)
  pl/background-color((if t bold italic))
  #[(face1 face2 &optional height) " ...
[...] [ Backtrace contains special characters I cannot paste in the GitHub issue.]
```

A quick look at Spaceline code seems to indicate that the documentation is actally wrong and that if :face is a form, it is not evaluated --- but I may be wrong, I'm very new to Elisp.

Thanks!

**Comment by jyp** [comment]
As far as I can tell @thblt is absolutely right. The documentation corresponding to the code can be found in spaceline.el and is: the following

```
- `:face', the face with which to render the segment; may either
  be a fixed face or one of the variables `default-face',
  `other-face' or `highlight-face' (default `default-face')
```
The corresponding code is this one:
```
           (face (if (memq face '(default-face other-face highlight-face line-face))
                     face `(quote ,face)))
```
It could be  changed as follows:

```
           (face (if (memq face '(default-face other-face highlight-face line-face))
                     face `(,@face)))
```

Then the documentation shoud be:

```
- `:face', the face with which to render the segment; may either
  be one of the variables `default-face',
  `other-face' or `highlight-face' (default `default-face') or a form evaluating to a face. Thus a fixed face should be quoted.
```

**Comment by m-janicki** [comment]
I also got tricked by this part of documentation.

Based on my current efforts I think that only one "dynamic" face might be used at a time, and it is defined via `spaceline-highlight-face-func` variable. Though my lisp skills are quite poor so hopefully I am wrong.

I would like to have 2 "dynamic" faces in my spaceline. One indicating if file was modified (this is already defined), and another one indicating if I am currently in god-mode. Is it currently possible?

**Comment by jyp** [comment]
@m-janicki With my PR you should be able to create/use any face dynamically.
