### ISSUE TITLE
Text length problem.

### ISSUE THREAD

**Issue by tek-nishi** [TheBB/spaceline#156]
I use Unicode characters  in mode-line

ex) １ ２ ３ ４

If calc text length

(length (format-mode-line ,format))

result 1. but this Unicode character's width is "2" 

I modified this

(string-width (format-mode-line ,format))

result 2. it is OK.

**Comment by deb0ch** [comment]
Hey,

Nice catch, thanks for reporting !

There's a PR on the way to fix that :thumbsup::sparkles:
