### ISSUE TITLE
Long buffer names aren't displayed

### ISSUE THREAD

**Issue by Apakollaps** [TheBB/spaceline#157]
When buffer names are over a certain length, buffer names disappear. I can reproduce it by:
Fails:
`emacs --geometry 100x50 abcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyz`
Works:
`emacs --geometry 110x50 abcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyz`

This might be dependent on font sizes etc., but changing the width should provoke the issue.

In contrast ` emacs -Q --geometry 10x50 abcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyz` shows part of the file name.

The example is contrived, but it comes from a real use case. When using a monitor rotated to portrait it becomes an issue quickly, especially with ediff.

The only tweak I've done to spaceline is disabling unicode characters, but I get the same behaviour with them enabled. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: nil (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(markdown html python helm auto-completion c-c++ better-defaults emacs-lisp gtags gnus org shell-scripts
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          semantic spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG PNG RSVG SOUND DBUS GCONF NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by TheBB** [comment]
This is intended behaviour. Segments are hidden if there's not enough space available (the buffer name is one of the most common culprits). See the discussion in https://github.com/TheBB/spaceline/commit/b1c41ddd290153fcc1df8f1d0fb54062e9943894 for a way to disable it.

**Comment by Apakollaps** [comment]
Thanks, works as intended. One suggestion is to make this variable customizable.
