### ISSUE TITLE
Modeline is blank

### ISSUE THREAD

**Issue by echelons6** [TheBB/spaceline#158]
I'm new to emacs + Spacemacs, I just did an install on Red Hat workstation 6.7. It says I'm using .200.9@25.2.1 (spacemacs) but the modeline area is blank. I'm not sure how to activate it, or what kind of information would be needed, were someone wanting to fix this issue.
Thanks for reading!

**Comment by TheBB** [comment]
There should be an error message in the messages buffer.

**Comment by echelons6** [comment]
My message buffer has the following:
Starting new Ispell process /usr/bin/hunspell with default dictionary...
Spacemacs is ready.
Loading /home/users/mcclist/.emacs.d/.cache/recentf...done
Open the quickhelp.
Skipping check for new version (reason: dotfile)
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [19 times]
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [8 times]
SPC C-g is undefined
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [2 times]
Error during redisplay: (eval (spaceline-ml-helm)) signaled (error "Invalid image type ‘xpm’") [9 times]
Text is read-onlyError during redisplay: (eval (spaceline-ml-helm)) signaled (error "Invalid image type ‘xpm’")
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [5 times]
Error during redisplay: (eval (spaceline-ml-helm)) signaled (error "Invalid image type ‘xpm’") [7 times]
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [3 times]
Mark set
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [4 times]
Error during redisplay: (eval (spaceline-ml-helm)) signaled (error "Invalid image type ‘xpm’") [7 times]
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [7 times]

**Comment by TheBB** [comment]
It looks like you're running on an emacs not compiled with image display support.

**Comment by echelons6** [comment]
Ooh I can believe that. I'll message the admin's about it. Thanks for looking!

**Comment by echelons6** [comment]
Hey sorry to re-open this issue, but admin's are saying a new version won't be rebuilt for awhile. Is there a version, or a setting I could use that doesn't require xpm support?

**Comment by deb0ch** [comment]
Shouldn't there be a way of disabling images in the modeline if Emacs wasn'nt compiled for it ?

Or consider that we are using a terminal Emacs ?
