### ISSUE TITLE
Right side of modeline truncated in GUI Emacs

### ISSUE THREAD

**Issue by hinrik** [TheBB/spaceline#166]
A few characters are cut off the right side of the modeline in all cases when running the Gtk+ version of Emacs. So in the default theme, the `hud` and part of the `buffer-position` segment are not shown. I do not have this issue in `emacs -nw`. I'm running Emacs 25.2.2.

![gui](https://user-images.githubusercontent.com/43533/33206833-ced8f6aa-d10b-11e7-98ce-126241d802ac.png)

![term](https://user-images.githubusercontent.com/43533/33206838-d27eb43e-d10b-11e7-8451-bd15b2237cce.png)

Example `init.el`:
```el
(eval-when-compile
  (require 'package)
  (setq package-enable-at-startup nil)
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  (require 'use-package))

(use-package spaceline-config
  :ensure spaceline
  :config (spaceline-spacemacs-theme))

```

**Comment by TheBB** [comment]
Same as https://github.com/TheBB/spaceline/issues/163 I believe.
