### ISSUE TITLE
Magit commit destroys the powerline

### ISSUE THREAD

**Issue by anka-213** [TheBB/spaceline#176]
#### Description :octocat:

Every time I make a commit using magit (`<spc> g s` and then `c c`), the powerline gets destroyed and replaced with a line containing just the title of the major-mode.

#### Reproduction guide :beetle:

- (Enable the `git` layer in spacemacs)
- Start Emacs
- Open a file in a git repository
- Open the git status window (`<SPC> g s`)
- Start making a commit (press `c c` in the status window)
- My beautiful powerline is gone. :(

*Observed behaviour:* :eyes: :broken_heart:

After starting a commit the powerline is gone. It stays gone even after committing.

The only ways I've found to restore the powerline are either to restart emacs or running `M-x spaceline-compile`.

![spaceline-not-working](https://user-images.githubusercontent.com/475451/35478837-58bddd36-03e8-11e8-8510-223944ab7a25.PNG)

*Expected behaviour:* :heart: :smile:

The powerline should stay in its place. Or at least be restored after finishing a commit.

![spaceline-working](https://user-images.githubusercontent.com/475451/35478838-58d607bc-03e8-11e8-9de2-7e9409ec92a9.PNG)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Spaceline version: spaceline-20171111.334
- Magit version: magit-20180124.1149
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml lua javascript
      (haskell :variables haskell-completion-backend 'ghci haskell-enable-hindent-style "johan-tibell")
      agda helm
      (auto-completion)
      emacs-lisp git github org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by solaryeti** [comment]
I'm getting this too. I don't get it with magit but I can reproduce it consistently in mu4e. I have a bookmark  for mu4e that has a particularly long search query, which are displayed in the global segment.

My spaceline segments are ordered something like this:
buffer-modified | buffer-id | flycheck | version-control | erc-track | process | <empty space> | selection-info | global | buffer-position

When I use this query the global segment disappears as well as all those to the left of it up to the buffer-id resulting in this:
buffer-modified | buffer-id | <empty space> | buffer-position

My guess is that this is some kind of overflow problem then because it happens consistently whenever the global segment expands to be greater than the available empty space.

**Comment by solaryeti** [comment]
I see that the spaceline--adjust-to-window will automatically hide segments if the modeline is longer than the window width. Probably the problem lies somewhere there?

I also found that setting spaceline-responsive to nil, which disables the above behaviour, solves the problem.

@anka-213 does setting spaceline-responsive solve it for you too? If so, then we might both be looking at the same issue.

**Comment by solaryeti** [comment]
I've tried with the lastest version and setting spaceline-responsive back to t. I have the same behaviour as I mentioned above where the segments get hidden and only display again if I run (spaceline-compile).

Do I understand spaceline--adjust-to-window correctly in that it should automatically show the hidden segments again once the total-length decreases? If so, I'm not sure why but this doesn't seem to be happening, at least in my case.

I don't know if it makes a difference but I'm building my own mode-line with spaceline-install, that has a few custom segments (mostly just some ideas that I liked from [domtronn/spaceline-all-the-icons.el](https://github.com/domtronn/spaceline-all-the-icons.el)). When I get a chance I'll see if I can replicate the issue with the default mode-line as well.

**Comment by TheBB** [comment]
If you use spaceline-install directly, maybe you need to adjust the priorities so that the segments you expect to be hidden first, will be. By default everything has the same priority so spaceline will be free to choose arbitrarily.

**Comment by solaryeti** [comment]
I've changed my spaceline config so that it consists only of this:
```
(require 'spaceline-config)
(spaceline-spacemacs-theme)
```
If the global segment gets extremely long then it gets hidden, as expected, but it doesn't get unhidden again afterwards unless I run spaceline-compile.

What conditions need to be met in order for it to be unhidden automatically?

**Comment by TheBB** [comment]
Yeah okay, I see the bug now. Lenths are updated when the segments are rendered, but segments that are hidden won't be rendered. This feature was designed more for varying window widths than varying segment lengths.

**Comment by TheBB** [comment]
Please try https://github.com/TheBB/spaceline/pull/188

**Comment by jsilve24** [comment]
I am on the development version 0.300 and I am still having this problem. Was this supposed to be fixed?

**Comment by duianto** [comment]
The modeline looks as expected for me in both `Manjaro` and `Windows`.

On the latest Spacemacs `develop` branch:
Use timeclock-mode-line-display in default bindings (#14713) https://github.com/syl20bnr/spacemacs/commit/d72e5129930f0f96805da96b95ca4166e02f80ae
with updated packages.

### Screenshots from Manjaro

#### Before committing

![VirtualBoxVM_2021-04-26_14-15-25](https://user-images.githubusercontent.com/13420573/116082749-0f7ea880-a69c-11eb-9712-06dcf883b806.png)

#### While committing

![VirtualBoxVM_2021-04-26_14-15-44](https://user-images.githubusercontent.com/13420573/116082787-186f7a00-a69c-11eb-98d0-3386d9fc08ae.png)

#### After having committed

![VirtualBoxVM_2021-04-26_14-16-08](https://user-images.githubusercontent.com/13420573/116082812-1dccc480-a69c-11eb-9e6d-026bb576d245.png)

<details><summary>
Manjaro, Click to expand
</summary><pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d72e51299)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre></details>

<details><summary>
Windows 10, Click to expand
</summary><pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d72e51299)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey c-c++ emacs-lisp
                 (git :variables)
                 helm html lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("c:/Users/username/org/"))
                 python shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre></details>

**Comment by jsilve24** [comment]
I am on Ubuntu 20.04
Using i3wm (not that I think that matters)

Staging is fine:
![spaceline1](https://user-images.githubusercontent.com/452422/116089587-04fae980-a671-11eb-837b-b9e27ee7cdcb.png)

Its when I enter the commit interface that the spaceline get clobbered and then doesn't come back. 
![spaceline2](https://user-images.githubusercontent.com/452422/116089666-16dc8c80-a671-11eb-8175-ae2da26b03e1.png)

Here is my .spacemacs file (extension changed to allow me to uplod to github)
[spacemacs.txt](https://github.com/TheBB/spaceline/files/6377366/spacemacs.txt)
