### ISSUE TITLE
Icons for separators?

### ISSUE THREAD

**Issue by hahuang65** [TheBB/spaceline#180]
Sorry, this isn't really an issue regarding spaceline, but I wanted to extract some of the separators so that I can use them in other places. Was wondering how those separators are rendered? I assumed it was font glyphs but perhaps I'm wrong?

Thank you for your time!

**Comment by TheBB** [comment]
The separators are XPM images defined in the powerline package. https://github.com/milkypostman/powerline/blob/master/powerline-separators.el
