### ISSUE TITLE
spaceline-compile in terminal emacsclient

### ISSUE THREAD

**Issue by jsoo1** [TheBB/spaceline#197]
Thanks for spaceline! Let me know if I need any more details for the issue! I get the following after running `spaceline-compile` in a terminal emacsclient, and the modeline disappears.
```
Unable to load color "2F3237" [4 times]
Error during redisplay: (eval (spaceline-ml-main)) signaled (void-function powerline-utf8-left) [13 times]
```

**Comment by jsoo1** [comment]
Hmm, closing. Looks like an interaction with another package. Pardon me.

**Comment by deb0ch** [comment]
Did you identify which other package, out of curiosity?
