### ISSUE TITLE
Mode Line disappears when scrolling

### ISSUE THREAD

**Issue by ForceFaction** [TheBB/spaceline#199]
When not at the top or bottom of a buffer the complete modeline disappears (It's just black).
I tested this with Emacs 26.1 and 27.0.50. If you need some Information please ask :D.

**Comment by deb0ch** [comment]
Well, you barely have any information 😅

Can you still reproduce? If yes, can you please provide a screenshot, information about your system and it's version, and most importantly a minimal configuration file to use with `emacs -Q -l your-file.el` that reproduce s the bug?

Without that I doubt that any of us or any (future) contributor will take the time to try investigating how to reproduce.

**Comment by ForceFaction** [comment]
I figured it out. It was (if i remember correctly) because i compiled without xpm support which lead to the minimap-widget (or whatever it is called) to make the modeline disappear when i'm not at the top or bottom of a buffer. So it was (as always :D) my fault ...

**Comment by deb0ch** [comment]
Thanks !
