### ISSUE TITLE
Round unicode characters in modeline cut off

### ISSUE THREAD

**Issue by glappen** [TheBB/spaceline#203]
I am not sure how to describe this exactly, so I'm going to post a screenshot.  

Basically, when I run spacemacs in terminal mode (with -nw option or when ssh'd into another machine) the round badges in the modeline and window numbers get cut off an are not showing the entire circle:

![46119529-5f8de980-c1d9-11e8-8a07-c25b1db52a1c](https://user-images.githubusercontent.com/92961/46208844-09fd2e00-c2fa-11e8-841e-f0f20b506670.png)

The rest of the modeline appears correct, so I don't think it's an issue with powerline fonts, but not sure what else it could be.

Any suggestions?

Thanks much!

**Comment by TheBB** [comment]
Honestly I don't think there's much I can do about this. You can try to copy and paste those characters into your shell prompt and I suspect they will look the same. It comes down to what font the terminal chooses to render those characters with, how wide they are, and what the terminal decides to do if they are too wide.

I tend to recommend turning off unicode symbols, for what it's worth.

**Comment by TheBB** [comment]
Since it looks like you are using Spacemacs you should consult Spacemacs documentation for that. I believe there's a dotfile variable for it.
