### ISSUE TITLE
feature request: support variable width fonts

### ISSUE THREAD

**Issue by neeasade** [TheBB/spaceline#207]
using a variable width 'mode-line font results in a big empty space at the right:

![bottom right](https://0x0.st/skR_.png)

**Comment by TheBB** [comment]
I'm not sure how easy this would be. To properly align the right hand side of the modeline, the
middle is filled with an amount of whitespace that needs to be carefully calculated (total width
minus width of left and right side). Variable width fonts would screw that up.

**Comment by neeasade** [comment]
Thanks for getting back to me. I suspected that might be the case/it would not be possible to reliably do cross platform. I might see if I can get it going on just my home maching with something like [txtw](https://github.com/baskerville/txtw), which can query width of text  strings.

**Comment by deb0ch** [comment]
Doesn't Emacs 26 introduce functions for calculating character and string width?
