### ISSUE TITLE
Line/column mode causes re-rendering performance problems

### ISSUE THREAD

**Issue by matthew-piziak** [TheBB/spaceline#215]
I've removed `spaceline` and my Emacs performance—especially the scrolling performance—is noticeably improved. I think this is due to rapid rerendering. Is it possible to remove the line/column segment and the right-size mini file-location indicator? I believe that that would fix the performance issues for me.

**Comment by matthew-piziak** [comment]
I am using `spaceline-20181223.2024` and Emacs 26.3.

**Comment by x-ji** [comment]
You can do it by defining your custom spaceline. See the end of the README file.

**Comment by matthew-piziak** [comment]
Yes, thank you, I believe that creating a custom mode-line without `line-column` would solve this.

In the meantime I've personally migrated to `doom-modeline`, which appears to be more efficient for my usecases, even with line and column tracking included.
