### ISSUE TITLE
How to activate

### ISSUE THREAD

**Issue by chookity-pokk** [TheBB/spaceline#243]
Ridiculous question here but I installed spaceline and I can't find a way to activate it. I am using Vanilla Emacs and for doom modeline I just call `doom-modeline-mode` and it works but I can't seem to find a similar function for spaceline.

**Comment by Icy-Thought** [comment]
You evaluate one of the two functions `(spaceline-spacemacs-theme)` or `(spaceline-emacs-theme)`.

**Comment by chookity-pokk** [comment]
Thank you!

**Comment by Icy-Thought** [comment]
Glad to help out!
