### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by MartenBE** [TheBB/spaceline#26]
Would it be possible to add a segment containing the encoding the buffer is currently in? (ANSI, UTF8, windows-1525, ...)? This would make it easy to see in which encoding a file is written.

**Comment by TheBB** [comment]
There is the `buffer-file-coding-system` segment already. By default Spacemacs uses just the line ending part of that information (unix, doc or mac) but you could use the full segment if you like.

**Comment by MartenBE** [comment]
I've tried replacing `((buffer-encoding-abbrev line-column) :separator " | ")` with `((buffer-file-coding-system buffer-encoding-abbrev line-column) :separator " | ")` but it does not changes

**Comment by TheBB** [comment]
Ah yeah, sorry, the segment name is `buffer-encoding`.

Could very well be that the README is messed up since I copied that code from a `defun`, I might have forgotten to remove the closing paren corresponding to the opening one in `defun`.

**Comment by TheBB** [comment]
Fixed: https://github.com/TheBB/spaceline/commit/8bade0a7c5cf48d2c1f71f4b8b32f396b0791ded
