### ISSUE TITLE
pyvenv integration

### ISSUE THREAD

**Issue by lalinsky** [TheBB/spaceline#28]
It would be very useful to see the current python virtualenv that is activated via [pyvenv](https://github.com/jorgenschaefer/pyvenv) and possibly add some menu to deactivate/switch it. I'd expect this to be similar to the current Git integration.

**Comment by santiagobasulto** [comment]
It'd be really nice to include the currently activated virtualenv in the mode line.

**Comment by TheBB** [comment]
https://github.com/TheBB/spaceline/commit/39ea3cab903daa9b90d4a767e6447cdf8c903ca8 should do it.

It should work with both pyvenv and pyenv (priority on the former). When mousing over the venv it should say which package it's using and the full path.

Let me know if it looks ugly in some themes. I wanted a different face for it.

**Comment by cpaulik** [comment]
Thanks. But it is unreadable in `spacemacs-dark´. Maybe @nashamri can theme it?

**Comment by TheBB** [comment]
Okay, I changed it to use specific foreground and distant-foreground, so now it should be at least readable in all themes.

**Comment by nashamri** [comment]
Just pushed https://github.com/nashamri/spacemacs-theme/commit/8f75815263ac93af3677cdb101dbcb0182b5e566 to fix this.

**Comment by santiagobasulto** [comment]
This works great. Thanks a lot @TheBB and @nashamri.
