### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by strugee** [TheBB/spaceline#33]
Tagging releases triggers the project to appear on MELPA Stable.

**Comment by TheBB** [comment]
I know, I'm waiting for it to *become* stable. :-)

**Comment by TheBB** [comment]
I'm not aware of any bugs, but there is still some documentation work to do.

**Comment by strugee** [comment]
@TheBB ah, okay. That makes sense. At this point I'm filing "please tag releases" issues out of habit :)

Thanks for being so responsive!

**Comment by TheBB** [comment]
1.0 is on MELPA stable now.

**Comment by strugee** [comment]
Thanks! \o/
