### ISSUE TITLE
Add mu4-alert segment

### ISSUE THREAD

**Issue by nixmaniack** [TheBB/spaceline#41]
Using [default modeline](https://github.com/iqbalansari/mu4e-alert/blob/89656f7e4e64c36f43db08205adef905e1a0aa3/mu4e-alert.el#L147) currently breaks the spaceline alignment , which adds a block at far right side as seen [here](https://gitter.im/syl20bnr/spacemacs?at=5666a8c5868b8da62a2555be)

**Comment by TheBB** [comment]
@nixmaniack Can you look at https://github.com/TheBB/spaceline/pull/51 ?

**Comment by nixmaniack** [comment]
Yep! Fixes it. No more empty stray block.
<img width="1280" alt="screen shot 2016-01-09 at 12 53 46 pm" src="https://cloud.githubusercontent.com/assets/542810/12215032/a98ca6a0-b6d0-11e5-996e-f67feb7286e5.png">

**Comment by nixmaniack** [comment]
It's merged!
