### ISSUE TITLE
fancy-battery-mode

### ISSUE THREAD

**Issue by justmytwospence** [TheBB/spaceline#42]
When I install `fancy-battery-mode`, I observe the same effect on the modeline as documented in #14.

**Comment by TheBB** [comment]
What's the value of `global-mode-string` in this case, then?

**Comment by justmytwospence** [comment]
```
("" persp-modestring
 (:eval mu4e-alert-mode-line)
 fancy-battery-mode-line)
```

**Comment by TheBB** [comment]
And this gives a `wrong-type-argument listp`? What's the error/backtrace exactly?

**Comment by justmytwospence** [comment]
Oh actually, error during redisply:

```
Fancy-Battery mode enabled
Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-function fancy-battery-powerline-face)
```

**Comment by TheBB** [comment]
Oh crap, I see I have inadvertently used a Spacemacs function. Will fix!

**Comment by TheBB** [comment]
Should work after https://github.com/TheBB/spaceline/commit/3990442b0b1f4f5975ae1bba3248fd89d4b5dff8
