### ISSUE TITLE
 Add segment for current input method

### ISSUE THREAD

**Issue by lunaryorn** [TheBB/spaceline#45]
Add a segment that shows `current-input-method` if set.  I'm using the following currently (see [my config](https://github.com/lunaryorn/dotfiles/blob/5600459837ae887b2f61f6012ddfc93bcf546fdf/spacemacs/.spacemacs.d/layers/lunaryorn/packages.el#L79)):

```cl
 (spaceline-define-segment lunaryorn-input-method
      "Current input method if non-default."
      (cond
       (current-input-method (propertize current-input-method-title
                                         'face 'bold))
       (default-input-method (propertize (nth 3 (assoc default-input-method
                                                       input-method-alist))
                                         'face 'italic))
       (t "none"))
      :enabled t)
    (add-to-list 'spaceline-right 'lunaryorn-input-method)
```

Active:
<img width="320" alt="bildschirmfoto 2015-12-15 um 12 31 20" src="https://cloud.githubusercontent.com/assets/224922/11809542/eaa729e2-a327-11e5-82fd-a08e18e7951b.png">

Inactive:
<img width="332" alt="bildschirmfoto 2015-12-15 um 12 34 04" src="https://cloud.githubusercontent.com/assets/224922/11809577/26cc9bd2-a328-11e5-9471-e4a92f1a669d.png">

No default method set:
<img width="325" alt="bildschirmfoto 2015-12-15 um 12 33 22" src="https://cloud.githubusercontent.com/assets/224922/11809566/133e63fc-a328-11e5-9470-d486ce5f1bf0.png">

What do you think?  Would you accept a pull request for this?  I'm with keeping a personal segment for this purpose, so I don't mind if you decline.  I just thought it'd be useful for others as well :relaxed:

**Comment by TheBB** [comment]
Yeah, I wouldn't mind, just PR it.

**Comment by lunaryorn** [comment]
@TheBB I've opened #47 :relaxed:
