### ISSUE TITLE
Automatically hide less-significant segments when window narrows

### ISSUE THREAD

**Issue by aaronjensen** [TheBB/spaceline#46]
Right now if my window is too narrow to display all my minor-modes and my line number on the right side of spaceline, the minor-modes win. I'd prefer the right side of the line to have precedent over the far right of the left side of the line. Ideally, the right side should just start to visually "overlap" the left side.

![resize](https://cloud.githubusercontent.com/assets/8588/11846454/9b68baa2-a3cd-11e5-9ec1-f30eb2aa1c3f.gif)

**Comment by robbyoconnor** [comment]
Is there any plans to fix this?

**Comment by TheBB** [comment]
Nothing concretely.

**Comment by robbyoconnor** [comment]
Yeah I can see the complexity in this

**Comment by twashing** [comment]
I'm having the same issue, so keen on this feature as well. Has there been any push to work on this?

I'm still green wrt elisp. But am willing to help if it will push things along.

**Comment by deb0ch** [comment]
This should be resolved by https://github.com/TheBB/spaceline/pull/133. I'm closing this, although @twashing your comment surprises me.

Please open a new issue if you're still having the issue you are talking about, as I really feel that the precise issue that was initially opened here has been resolved by https://github.com/TheBB/spaceline/pull/133.
