### ISSUE TITLE
spaceline error on 0.105.0

### ISSUE THREAD

**Issue by 877381872** [TheBB/spaceline#49]
Here is a error with spaceline on 0.105.0.
Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-variable spacemacs-mode-line-new-version-lighterp) 
When I open the emacs, the error appeared.And the spaceline was invalid。
How I can do something to fix it ??
thanks a lot 
Just now, I found when I use split screen function. The error appeared.

**Comment by mastokley** [comment]
Hello,

I'm getting this same error. Was it resolved by updating to 0.105.7?

**Comment by mastokley** [comment]
For me, this was resolved by updating to 0.105.8.

**Comment by 877381872** [comment]
yes, it is OK when update to the latest version.   :)

**Comment by TheBB** [comment]
This was bug in Spacemacs that was fixed in 0.105.2.
