### ISSUE TITLE
spaceline-toggle-version-control-on doesn't work

### ISSUE THREAD

**Issue by mcandre** [TheBB/spaceline#55]
I don't see my git branch listed in spaceline when I use `(spaceline-toggle-version-control-on)`. Am I missing an Emacs package?

**Comment by TheBB** [comment]
Do you have `vc-mode` enabled?

**Comment by mcandre** [comment]
No, I had disabled it for... reasons.

Once I re-enable vc-mode, spaceline with vc-mode works once more.
