### ISSUE TITLE
Powerline height

### ISSUE THREAD

**Issue by mclearc** [TheBB/spaceline#60]
Sorry if this is a simple question, but I can't seem to increase the size (height) of the modeline. I suppose that I'm supposed to adjust `powerline-height`, but it seems that any value I give it (e.g. '1.4' or integers such as '1' or '2') either renders the whole modeline blank or makes it bigger but with weird blank boxes in place of the separators. I assume I'm just doing this incorrectly? Any ideas?

**Comment by TheBB** [comment]
Have you remembered to run `powerline-reset` after changing it?

**Comment by mclearc** [comment]
I have. Is the command supposed to be something like `setq powerline-height 1.4`?

**Comment by TheBB** [comment]
```elisp
(setq powerline-height 19)
(powerline-reset)
```

1.4 seems quite low. The unit is supposed to be pixels.

**Comment by mclearc** [comment]
Looks like it was a combination of errors then. That seems to have fixed it, thanks.
