### ISSUE TITLE
flycheck-pos-tip conflicts with spaceline

### ISSUE THREAD

**Issue by user471** [TheBB/spaceline#62]
`Spaceline` disappears when `flycheck-pos-tip` shows up
before
![1](https://cloud.githubusercontent.com/assets/5988253/13215262/215ab12a-d965-11e5-812d-a6e9a82fcfe4.png)
after
![2](https://cloud.githubusercontent.com/assets/5988253/13215263/215d95e8-d965-11e5-85d1-7d1afec24b88.png)

**Comment by TheBB** [comment]
It doesn't disappear. It looks like it just determines that the window is no longer active, i.e. it looks like the modeline in any other inactive window.

I don't know why that happens, though. I can't reproduce.

**Comment by user471** [comment]
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. 8bdc80b)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/")
 git emacs-lisp haskell colors javascript csharp dash org purescript syntax-checking markdown elm)
```

```
It looks like it just determines that the window is no longer active
```
Is it possible to disable this? So it would not determine windows activity.

**Comment by user471** [comment]
Also, `spaceline` returns back only after `Alt-Tab` or swithing buffer.

**Comment by TheBB** [comment]
> I only have one emacs window.

Most people have more. But yeah, I can add an option to disable active/inactive checking if you'd like.

For now a workaround would be:

```elisp
(defun my-active-p (&rest args) t)
(advice-add 'powerline-selected-window-active :around 'my-active-p)
```

**Comment by user471** [comment]
It works, thanks.
>I can add an option to disable active/inactive checking if you'd like.
The workaround works so I think it isn't necessary.
