### ISSUE TITLE
When used with Theme-Changer, wave style becomes white.

### ISSUE THREAD

**Issue by jojojames** [TheBB/spaceline#64]
Using https://github.com/hadronzoo/theme-changer, with spaceline. When theme changes from one to the other, the spaceline is redrawn with the new theme but the "waves" become clipped with white.

<img width="1631" alt="screenshot 2016-02-23 16 37 44" src="https://cloud.githubusercontent.com/assets/1227856/13271815/6d29b5e6-da4c-11e5-9e1d-078dafcb179a.png">

**Comment by TheBB** [comment]
Have you remembered to call `(powerline-reset)` after?

**Comment by jojojames** [comment]
Thanks, works for me.

  (defun reset-line--change-theme (&rest args)
    (powerline-reset))
  (advice-add 'change-theme :after #'reset-line--change-theme)
