### ISSUE TITLE
spaceline-toggle-line does not have any effect

### ISSUE THREAD

**Issue by sooheon** [TheBB/spaceline#66]
For some reason, `spaceline-toggle-line-column` functions as expected, but I can't toggle just the line or just the column by themselves. 

#### Info

Emacs 24.5.1 on OSX El Cap, Spaceline 1.1.2, Spacemacs v.0.105.13

**Comment by TheBB** [comment]
Are you using these segments in your modeline? Note they are not included in the default theme, so unless you use a different one there's no reason that those toggles should do anything.

https://github.com/TheBB/spaceline/blob/master/spaceline-config.el#L54

**Comment by sooheon** [comment]
Ah I see. So the correct way to enable the ones I want is to have a whole new `spaceline-install` call?

**Comment by TheBB** [comment]
Or you can edit the values of `spaceline-left` and `spaceline-right` manually. I was planning a simpler API for this but so far I haven't had time to realize it.

**Comment by sooheon** [comment]
Got it. If `setq spaceline-left ...` work that seems simple enough.
