### ISSUE TITLE
anzu mode gets displayed twice 

### ISSUE THREAD

**Issue by jwintz** [TheBB/spaceline#69]
Hello,

I've enabled `global-anzu-mode` as `spaceline` provides a nice integration  of it. However, when performing a search, the counter gets displayed twice.

![screen shot 2016-03-15 at 10 50 20](https://cloud.githubusercontent.com/assets/3277054/13773977/9e781dda-ea9c-11e5-9ed3-2d9bbc6503eb.png)

How can I fix this ?

Thanks.

**Comment by TheBB** [comment]
You probably have anzu's modeline functionality and Spaceline's enabled at the same time. You should turn off anzu's.

**Comment by TheBB** [comment]
`(setq anzu-cons-mode-line-p nil)`

**Comment by TheBB** [comment]
This is the same kind of problem as the previous one: you're not taking care of disabling the built-in modeline functionality of the modes that you prefer to use via Spaceline instead.

**Comment by jwintz** [comment]
That fixed it. Thanks again !
