### ISSUE TITLE
Integration with anzu

### ISSUE THREAD

**Issue by swarnendubiswas** [TheBB/spaceline#7]
I use anzu with the default Emacs 24.5 package, and now I have added spaceline. Nice work. The problem is that anzu info now shows up twice in the mode-line, once for anzu and once for spaceline. I can avoid this by setting spaceline-anzu-p to nil. Is it possible to load anzu, turn off anzu's modeline presentation and use spaceline's instead?

In the attached snapshot, the left one is due to anzu, whereas the right one is due to spaceline.
![screenshot-1](https://cloud.githubusercontent.com/assets/7343807/10151086/f298f192-6611-11e5-9b12-04846ad5e3c5.png)

**Comment by TheBB** [comment]
Can you try setting `anzu-cons-mode-line-p` to `nil`? [Here](https://github.com/syl20bnr/spacemacs/blob/master/layers/+distribution/spacemacs/packages.el#L528) is Spacemacs' anzu configuration.

**Comment by swarnendubiswas** [comment]
Thanks, that tip works.
