### ISSUE TITLE
version control segment doesn't update on branch change

### ISSUE THREAD

**Issue by mclearc** [TheBB/spaceline#70]
I've noticed that when I change branches the branch name won't update in spaceline. I have to close and open the buffer to get it to do so. This may perhaps be related to the discussion in #18 but I'm not sure.

**Comment by TheBB** [comment]
I don't think this is Spaceline's problem. It only reads the branch from vc. If vc can't keep itself up to date, or if something else can't make sure to keep it up to date, then I'm liable to think the bug is elsewhere.

**Comment by mclearc** [comment]
You're right. I didn't have `auto-revert-check-vc-info` set to non-nil. That has fixed it. Sorry for the noise.
