### ISSUE TITLE
Void-function spaceline-ml-helm

### ISSUE THREAD

**Issue by igorepst** [TheBB/spaceline#75]
Hi, on the latest build from Melpa (20160510.542) I get `Error during redisplay: (eval (spaceline-ml-helm)) signaled (void-function spaceline-ml-helm)`
Could you fix this, please?
Thank you

**Comment by TheBB** [comment]
Are you using `spaceline-helm-mode`?

**Comment by TheBB** [comment]
Ah, I can reproduce by not using that mode. Let me check.

**Comment by TheBB** [comment]
Should be fixed now, thanks.

**Comment by igorepst** [comment]
Fixed, thanks!
