### ISSUE TITLE
Special character messes up segment alignment

### ISSUE THREAD

**Issue by angrybacon** [TheBB/spaceline#81]
Is that special character somehow changing font properties for subsequent text?

![screen shot 2016-06-10 at 11 06 05](https://cloud.githubusercontent.com/assets/5608624/15959579/b4ac6478-2efb-11e6-8db7-43e66d368217.png)
![screen shot 2016-06-10 at 11 06 56](https://cloud.githubusercontent.com/assets/5608624/15959578/b4abfca4-2efb-11e6-97db-b4c87c1c774a.png)

**Comment by TheBB** [comment]
It could mess up the alignment of the right hand side if it doesn't have a standard width, yes. If so it is probably an issue with powerline and `powerline-width`.

**Comment by angrybacon** [comment]
Probably fixed using the Font Awesome character instead. Thank you
