### ISSUE TITLE
Add a customizable indicator to replace the bullet next to flycheck error counts

### ISSUE THREAD

**Issue by angrybacon** [TheBB/spaceline#82]

**Comment by TheBB** [comment]
Did you have anything specific in mind?

**Comment by angrybacon** [comment]
Mmh, in my case I wanted to add a space between the bullet and the error count. But it could serve a greater number of person if the indicator was just a variable to be changed.

**Comment by TheBB** [comment]
Okay so you are talking about the bullet.

**Comment by TheBB** [comment]
Fixed in https://github.com/TheBB/spaceline/commit/07db5e82b37272b87fd63ca8a3c21d38c15e10d2

**Comment by angrybacon** [comment]
Awesome! Thank you for your responsiveness.  👌
