### ISSUE TITLE
The erc-track segment doesn't use a different face when a nick is mentioned

### ISSUE THREAD

**Issue by ionrock** [TheBB/spaceline#83]
In erc-tracking the mode line gets a bold face when someone mentions your nick. The erc-track segment doesn't use this and instead just uses the erc-modified-channels-alist directly.

**Comment by vincentbernat** [comment]
This should be fixed by ca85233b443216f8519c401c58af6807b6d31740.

**Comment by deb0ch** [comment]
I don't use erc so I can't really test for sure but it indeed seems that this issue was resolved in https://github.com/TheBB/spaceline/commit/ca85233b443216f8519c401c58af6807b6d31740.

Please re-open if it is not the case.
